import { expect, test } from '@playwright/test'

test('landing, arena connection, mouse capture, movement and cleanup', async ({ page, context }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Find your line')
  await page.screenshot({ path: testInfo.outputPath('landing.png'), fullPage: true })
  await page.getByRole('link', { name: 'Enter training' }).click()
  await expect(page.getByRole('status')).toContainText('Connected')
  await expect(page.locator('canvas')).toBeVisible()
  const second = await context.newPage()
  second.on('pageerror', (error) => { errors.push(error.message); console.error('Second tab:', error.message) })
  second.on('console', (message) => { if (message.type() === 'error') console.error(message.text()) })
  await second.goto('/play')
  await expect(second.getByRole('status')).toContainText('Connected', { timeout: 20000 })
  await expect(page.getByRole('status')).toContainText('2 / 8 PLAYERS')
  await second.close()
  await expect(page.getByRole('status')).toContainText('1 / 8 PLAYERS')
  const initial = await page.getByTestId('position').innerText()
  await page.getByRole('button', { name: 'Take control' }).click()
  await expect(page.locator('.crosshair')).toBeVisible()
  await page.keyboard.down('KeyW')
  await expect(page.getByTestId('position')).not.toHaveText(initial)
  await page.keyboard.up('KeyW')
  await page.screenshot({ path: testInfo.outputPath('arena.png') })
  await page.keyboard.press('Escape')
  await expect(page.locator('.crosshair')).toBeHidden()
  await page.getByRole('link', { name: 'Leave arena' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Find your line')
  expect(errors).toEqual([])
})
