import { test, expect } from '@playwright/test'

test('mode selection stays in the lobby until Play and shows one primary action', async ({ page }, info) => {
  await page.goto('/')
  await expect(page.locator('main.lobby')).toHaveAttribute('data-ready', 'true')
  await page.getByRole('button', { name: 'Practice', exact: true }).click()
  await expect(page).toHaveURL('/')
  await expect(page.getByRole('button', { name: 'Practice', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.play-button')).toHaveCount(1)
  await expect(page.locator('.play-button')).toHaveText(/Play Practice/)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: info.outputPath('desktop-lobby.png'), animations: 'disabled' })
  await page.getByRole('button', { name: 'Play Practice', exact: true }).click()
  await expect(page.locator('main.arena')).toHaveAttribute('data-phase', 'playing', { timeout: 30000 })
  const box = (await page.locator('.radar').getAttribute('viewBox'))!.split(' ').map(Number)
  expect(box[2]).toBe(56)
  const id = await page.locator('main.arena').getAttribute('data-player-id')
  const actor = page.locator(`[data-actor="${id}"]`)
  expect(box[0]! + 28).toBeCloseTo(Number(await actor.getAttribute('data-x')), 0)
  expect(box[1]! + 28).toBeCloseTo(-Number(await actor.getAttribute('data-z')), 0)
  await expect(page.locator('.telemetry')).toHaveCSS('clip-path', 'inset(50%)')
  await page.screenshot({ path: info.outputPath('desktop-hud.png') })
  await page.keyboard.press('Escape')
  await page.screenshot({ path: info.outputPath('desktop-pause.png') })
})

test('touch preferences persist and largest controls fit a small landscape phone', async ({ browser }, info) => {
  test.setTimeout(60000)
  const context = await browser.newContext({ viewport: { width: 667, height: 375 }, isMobile: true, hasTouch: true })
  const page = await context.newPage()
  try {
    await page.goto('http://127.0.0.1:3001/')
    await page.screenshot({ path: info.outputPath('phone-lobby.png') })
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(page.getByRole('button', { name: 'Play Solo vs Bots', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.locator('main.lobby')).toHaveCount(1)
    await page.screenshot({ path: info.outputPath('portrait-lobby.png') })
    await page.setViewportSize({ width: 667, height: 375 })
    await page.getByRole('button', { name: 'CONTROLS', exact: true }).tap()
    await page.getByRole('slider', { name: 'Touch control size' }).fill('120')
    await page.getByRole('slider', { name: 'Touch control opacity' }).fill('45')
    await page.getByRole('button', { name: 'CLOSE', exact: true }).tap()
    await page.reload()
    await page.getByRole('button', { name: 'CONTROLS', exact: true }).tap()
    await expect(page.getByRole('slider', { name: 'Touch control size' })).toHaveValue('120')
    await expect(page.getByRole('slider', { name: 'Touch control opacity' })).toHaveValue('45')
    await page.getByRole('button', { name: 'CLOSE', exact: true }).tap()
    await page.getByRole('button', { name: 'Practice', exact: true }).tap()
    await page.getByRole('button', { name: 'Play Practice', exact: true }).tap()
    await expect(page.getByRole('button', { name: 'Fire', exact: true })).toBeVisible({ timeout: 30000 })
    await expect(page.locator('.touch-controls')).toHaveCSS('--touch-scale', '1.2')
    await expect(page.locator('.touch-controls')).toHaveCSS('--touch-opacity', '0.45')
    for (const name of ['Fire', 'Aim', 'Reload', 'Crouch', 'Pause']) {
      const box = (await page.getByRole('button', { name, exact: true }).boundingBox())!
      expect(box.x).toBeGreaterThanOrEqual(0); expect(box.y).toBeGreaterThanOrEqual(0)
      expect(box.x + box.width).toBeLessThanOrEqual(667); expect(box.y + box.height).toBeLessThanOrEqual(375)
    }
    await page.screenshot({ path: info.outputPath('phone-largest-controls.png') })
    await page.getByRole('button', { name: 'Pause', exact: true }).tap()
    await page.getByRole('button', { name: 'Controls', exact: true }).tap()
    await page.getByRole('slider', { name: 'Touch control size' }).focus()
    await page.keyboard.press('ArrowDown')
    await expect(page.getByRole('slider', { name: 'Touch control size' })).toHaveValue('115')
    await page.getByRole('button', { name: 'Reset controls', exact: true }).tap()
    await expect(page.getByRole('slider', { name: 'Touch control size' })).toHaveValue('100')
    await page.getByRole('button', { name: 'Resume training', exact: true }).tap()
    await expect(page.locator('.touch-controls')).toHaveCSS('--touch-scale', '1')
    await expect(page.locator('.touch-controls')).toHaveCSS('--touch-opacity', '0.8')
  } finally { await context.close() }
})

test('mobile elimination panel counts down, identifies the opponent, and clears on respawn', async ({ browser }, info) => {
  test.setTimeout(120000)
  const context = await browser.newContext({ viewport: { width: 667, height: 375 }, isMobile: true, hasTouch: true })
  const page = await context.newPage()
  try {
    await page.goto('http://127.0.0.1:3001/play?mode=solo')
    await page.getByRole('button', { name: 'Start match', exact: true }).tap()
    const panel = page.getByTestId('respawn-overlay')
    await expect(panel).toBeVisible({ timeout: 90000 })
    await expect(panel).toContainText('You were eliminated.')
    await expect(panel).toContainText('Eliminated by')
    await expect(page.getByTestId('respawn-countdown')).toHaveText(/[123]s/)
    const card = (await page.getByRole('region', { name: 'Respawning' }).boundingBox())!
    expect(card.x).toBeGreaterThanOrEqual(0); expect(card.y).toBeGreaterThanOrEqual(0)
    expect(card.x + card.width).toBeLessThanOrEqual(667); expect(card.y + card.height).toBeLessThanOrEqual(375)
    await page.screenshot({ path: info.outputPath('phone-respawn.png') })
    await expect(panel).toBeHidden({ timeout: 6000 })
    await expect(page.getByTestId('health')).toContainText('100')
  } finally { await context.close() }
})
