packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  '@parcel/watcher': true
  msgpackr-extract: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@babylonjs/core@9.29.0'
  - '@babylonjs/loaders@9.29.0'
