import type { CampaignMission } from './campaign.js'
import type { CampaignTask, CampaignTaskKind } from './campaignTasks.js'
import { operationArena, type OperationEnvironment, type OperationLocation } from './operationArenas.js'

type TaskPlan = [CampaignTaskKind, OperationLocation, string, number?]
interface Chapter {
  id:string; title:string; arena:string; environment:OperationEnvironment
  kind:CampaignMission['kind']; companion?:string; briefing:string; debrief:string; tasks:TaskPlan[]
}
const chapters:Chapter[]=[
  {id:'blackout',title:'Blackout',arena:'CALDER SUBSTATION',environment:'industrial',kind:'sabotage',briefing:'The district is being tracked through Calder’s power network. Take the western control room, cut two feeds, and hold the uplink while Control wipes the surveillance archive.',debrief:'The grid is dark. Control has recovered the location of a detained railway engineer.',tasks:[['clear','west','Secure the control room'],['interact','west','Isolate the western feed',4],['plant','east','Rig the backup transformer',4],['defend','center','Hold the archive uplink',24],['extract','exit','Leave before the grid collapses',5]]},
  {id:'iron-route',title:'Iron route',arena:'ASH RAIL YARD',environment:'industrial',kind:'extraction',companion:'Vale',briefing:'Engineer Vale knows which trains carry the weapons. Sweep the yard, retrieve the signal key, and escort Vale while the enemy tries to retake the dispatch post.',debrief:'Vale has identified the enemy’s northern supply schedule. A reservoir on that route has been mined.',tasks:[['clear','west','Clear the dispatch squad'],['interact','center','Retrieve the signal key',3],['rescue','east','Release engineer Vale',3],['defend','north','Protect the route upload',25],['extract','exit','Escort Vale out of the yard',5]]},
  {id:'cold-water',title:'Cold water',arena:'VESPER RESERVOIR',environment:'coastal',kind:'defusal',briefing:'Charges threaten the district’s water supply. Recover the wiring diagram, disarm both charges before their timers expire, and secure the pump controls against a counterattack.',debrief:'The reservoir is safe. The detonators came from a remote relay station.',tasks:[['interact','south','Recover the wiring diagram',3],['defuse','west','Disarm the intake charge',5],['clear','east','Eliminate the pump guards'],['defuse','north','Disarm the pressure charge',6],['defend','center','Protect the pump restart',22],['extract','exit','Reach the service gate',5]]},
  {id:'ghost-frequency',title:'Ghost frequency',arena:'PINE LOGGING TOWN',environment:'forest',kind:'intelligence',briefing:'A relay hidden in an abandoned logging town coordinates the hostile patrols. Collect its encryption key, seize the antenna crew, and keep the receiver online long enough to intercept the next transmission.',debrief:'The transmission reveals an airfield preparing a fresh delivery.',tasks:[['interact','south','Collect the encryption key',3],['clear','west','Silence the antenna crew'],['interact','north','Align the listening array',4],['defend','center','Capture the transmission',30],['plant','east','Rig the hostile relay',3],['extract','exit','Withdraw through the tree line',5]]},
  {id:'broken-wing',title:'Broken wing',arena:'KESTREL CIVIL AIRPORT',environment:'airfield',kind:'assault',briefing:'Stop the next weapons delivery. Retake the civilian terminal, sabotage two supply points, then hold the runway controls until the inbound flight is diverted.',debrief:'The delivery has been diverted. Ground forces are falling back through a crowded market.',tasks:[['clear','west','Retake the arrivals terminal'],['plant','east','Rig the aviation fuel feed',4],['plant','north','Rig the cargo stores',4],['defend','center','Hold the runway controls',28],['extract','exit','Reach the perimeter breach',5]]},
  {id:'market-fire',title:'Market fire',arena:'SAFFRON QUARTER',environment:'urban',kind:'defusal',briefing:'A retreating demolition team has left a charge in the market. Find its code, clear a route to the device, and protect the evacuation broadcast once it is disarmed.',debrief:'The market evacuation is underway. A courier is trapped in the old quarry.',tasks:[['clear','west','Break the market blockade'],['interact','west','Recover the disarm code',3],['defuse','east','Disarm the market device',6],['defend','north','Protect the evacuation broadcast',26],['extract','exit','Exit through the service court',5]]},
  {id:'deep-cut',title:'Deep cut',arena:'REDSTONE QUARRY',environment:'desert',kind:'extraction',companion:'Mara',briefing:'Courier Mara holds the enemy’s command roster. Eliminate the quarry security detail, open the dispatch channel, and bring her through the machinery yard under counterattack.',debrief:'Mara’s roster identifies the commander of the southern listening post.',tasks:[['clear','west','Clear the quarry security detail'],['interact','center','Open the dispatch channel',4],['rescue','north','Recover courier Mara',3],['defend','east','Hold the machinery yard',30],['extract','exit','Escort Mara to the south gate',5]]},
  {id:'silent-current',title:'Silent current',arena:'TIDAL OLD TOWN',environment:'coastal',kind:'intelligence',briefing:'A listening post in the deserted seaside town is about to erase its records. Take the code room, copy two archives, and prevent the recovery squad from interrupting the final transfer.',debrief:'The archives reveal a plan to destroy the district’s fuel reserves.',tasks:[['clear','west','Capture the code room'],['interact','east','Copy the patrol archive',5],['defend','center','Hold the transfer link',32],['interact','north','Retrieve the command ledger',5],['extract','exit','Leave along the seawall',5]]},
  {id:'burn-line',title:'Burn line',arena:'EMBER FUEL DEPOT',environment:'industrial',kind:'defusal',briefing:'The fuel depot has been prepared for demolition. Kill the security squad, recover the valve sequence, and disarm two linked charges before sealing the site.',debrief:'The fuel reserves are intact. Control has lost contact with an isolated field station.',tasks:[['clear','west','Eliminate depot security'],['interact','west','Recover the valve sequence',3],['defuse','east','Disarm the first linked charge',5],['defuse','north','Disarm the second linked charge',6],['defend','center','Hold while the valves seal',24],['extract','exit','Reach the emergency exit',5]]},
  {id:'long-watch',title:'Long watch',arena:'ALDER NEIGHBOURHOOD',environment:'forest',kind:'defense',briefing:'An emergency relay in the evacuated neighbourhood is still transmitting, but its guards have gone silent. Reconnect its antenna, sweep the perimeter squads, and hold two positions against the response force.',debrief:'The station is secure. A captured surveyor can identify a hidden supply route.',tasks:[['interact','south','Reconnect the field antenna',4],['clear','west','Sweep the western perimeter'],['defend','center','Hold the neighbourhood relay',30],['clear','east','Break the flanking squad'],['defend','north','Protect the final transmission',35],['extract','exit','Withdraw to the forest gate',5]]},
  {id:'dust-trail',title:'Dust trail',arena:'DUNE CARAVAN TOWN',environment:'desert',kind:'extraction',companion:'Tariq',briefing:'Surveyor Tariq mapped a route through the dunes. Recover his survey charts, clear the occupied survey office, then protect him while Control verifies the escape route.',debrief:'The survey charts reveal a second weapons shipment waiting at a container terminal.',tasks:[['interact','south','Retrieve the survey charts',3],['clear','north','Clear the occupied survey office'],['rescue','north','Release surveyor Tariq',3],['defend','west','Verify the escape route',28],['interact','east','Open the town escape route',4],['extract','exit','Escort Tariq beyond the perimeter',5]]},
  {id:'sealed-cargo',title:'Sealed cargo',arena:'EAST CONTAINER TERMINAL',environment:'coastal',kind:'sabotage',briefing:'The second shipment is split between two compounds. Capture the manifest, eliminate both guard details, and arm the stores before fighting back to the safe zone.',debrief:'Both stores are ready for demolition. The escape reveals a fortified civic command post.',tasks:[['interact','south','Copy the container manifest',4],['clear','west','Clear the western shipment'],['plant','west','Arm the western stores',4],['clear','east','Clear the eastern shipment'],['plant','east','Arm the eastern stores',4],['defend','north','Hold the demolition link',22],['extract','exit','Reach the remote detonation zone',5]]},
  {id:'hard-reset',title:'Hard reset',arena:'CIVIC DATA EXCHANGE',environment:'urban',kind:'intelligence',briefing:'The civic exchange controls the enemy’s surveillance net. Secure its access key, hold two upload points, and leave with the command archive before the backup link is restored.',debrief:'The archive exposes an emergency transmitter at a remote landing strip.',tasks:[['clear','west','Take the access-key squad'],['interact','west','Recover the exchange key',3],['defend','center','Upload the network override',26],['interact','east','Retrieve the command archive',5],['defend','north','Purge the backup link',32],['extract','exit','Leave through the service exit',5]]},
  {id:'last-approach',title:'Last approach',arena:'MORROW LANDING STRIP',environment:'airfield',kind:'defense',briefing:'Enemy reinforcements are using a remote strip. Clear its support crew, disable the navigation beacon, and hold the transmitter until Control confirms the air corridor is closed.',debrief:'The air corridor is closed. A medic has been cornered in a coastal aid station.',tasks:[['clear','east','Clear the support crew'],['plant','north','Rig the navigation beacon',5],['interact','west','Seize the flight-control codes',4],['defend','center','Hold the emergency transmitter',40],['extract','exit','Reach the runway escape lane',5]]},
  {id:'white-flag',title:'White flag',arena:'BREAKWATER HOSPITAL',environment:'coastal',kind:'extraction',companion:'Sen',briefing:'Medic Sen has been cut off with vital evacuation records. Recover the radio battery, break the clinic cordon, and protect the medic through two pickup checks.',debrief:'Sen and the records are safe. The enemy’s retreat runs through an explosive-laden workshop.',tasks:[['interact','south','Recover the radio battery',3],['clear','east','Break the clinic cordon'],['rescue','east','Recover medic Sen',3],['defend','center','Hold for the pickup check',25],['defend','north','Protect the evacuation relay',30],['extract','exit','Escort Sen to the safe route',5]]},
  {id:'chain-reaction',title:'Chain reaction',arena:'FORGE WORKS',environment:'industrial',kind:'defusal',briefing:'A retreating unit is priming Forge Works. Disarm the linked workshop devices, remove the command squad, and keep the shutdown console secure until the plant is stable.',debrief:'Forge Works is stable. Only the occupied civic centre remains between the district and an open evacuation route.',tasks:[['interact','south','Read the shutdown sequence',3],['defuse','west','Disarm the workshop trigger',6],['clear','east','Eliminate the command squad'],['defuse','north','Disarm the reserve trigger',6],['defend','center','Protect the shutdown console',35],['extract','exit','Leave the secured works',5]]},
  {id:'open-horizon',title:'Open horizon',arena:'HORIZON OLD TOWN',environment:'desert',kind:'assault',briefing:'The enemy has made the old civic centre its final command position. Clear both defensive squads, recover the evacuation codes, and hold the ridge relay through the last counterattack. Then open the district’s escape route.',debrief:'The command network is down, the supply chain is broken, and the evacuation route is open. Operation Breakwater is complete.',tasks:[['clear','west','Break the outer defensive squad'],['interact','west','Recover the evacuation codes',4],['clear','east','Break the inner defensive squad'],['plant','east','Rig the command stores',5],['defend','north','Hold against the final counterattack',45],['interact','center','Open the district evacuation route',6],['extract','exit','Reach the final extraction',6]]},
]

export const OPERATION_MISSIONS: readonly CampaignMission[] = chapters.map((chapter,index)=>{
  const {world,points,guards}=operationArena(chapter.id,chapter.arena,chapter.environment,index)
  const availableWaves=[[12,13,14,15],[16,17,18,19]]
  const groups:Partial<Record<OperationLocation,number[]>>={west:[0,1,2,3],east:[4,5,6,7],north:[8,9,10,11]}
  const tasks:CampaignTask[]=chapter.tasks.map(([kind,location,title,seconds],i)=>{
    const previous=i?points[chapter.tasks[i-1]![1]]:points.insertion,position=points[location]
    const waveIndex=kind==='defend'?availableWaves.findIndex(group=>group.every(n=>Math.hypot(guards[n]!.x-previous.x,guards[n]!.z-previous.z)>22&&Math.hypot(guards[n]!.x-position.x,guards[n]!.z-position.z)>18)):-1
    const reinforcements=waveIndex>=0?availableWaves.splice(waveIndex,1)[0]:undefined
    const durationMs=(seconds??1)*1000,radius=kind==='defend'?7:kind==='extract'?5:2.8
    const instruction=kind==='clear'?'Eliminate the marked squad, then enter the objective circle.':kind==='defend'?`Stay in the circle for ${seconds} seconds. Nearby hostiles contest the zone; leaving resets the hold.`:kind==='defuse'?'Reach the device before its countdown ends. Stay in its circle to disarm it automatically.':kind==='rescue'?`Enter ${chapter.companion}’s circle, then keep them within 18 metres.`:kind==='extract'?chapter.companion?`Reach the exit with ${chapter.companion} and stay inside the circle.`:'Reach the exit and hold the circle until extraction is confirmed.':'Enter the objective circle and stay there until the action completes.'
    return {id:`${chapter.id}-${i+1}`,kind,title,instruction,position,durationMs,radius,
      ...(kind==='defuse'?{timeLimitMs:120000}:{}),...(kind==='clear'?{enemyIds:groups[location]!.map(n=>`bot-${n}`)}:{}),...(reinforcements?{reinforcements}:{})}
  })
  const fixtures=tasks.filter(t=>['interact','defuse','plant'].includes(t.kind)).filter((t,i,all)=>all.findIndex(other=>other.position===t.position)===i).map((t,i)=>({id:`objective-terminal-${i}`,x:t.position.x+1.8,y:.6,z:t.position.z,width:.7,height:1.2,depth:.5,material:'metal' as const}))
  world.solids=[...world.solids,...fixtures];world.colliders=[...world.colliders,...fixtures]
  const rescue=tasks.find(t=>t.kind==='rescue'),first=tasks[0]!,last=tasks.at(-1)!
  return {id:chapter.id,chapter:String(index+4).padStart(2,'0'),title:chapter.title,operation:'Operation Breakwater',kind:chapter.kind,
    briefing:chapter.briefing,debrief:chapter.debrief,companion:chapter.companion??'',successTitle:'Objective accomplished.',
    relay:first.position,captive:rescue?.position??tasks[1]!.position,extraction:last.position,
    spawn:points.insertion,rescueSpawn:first.position,escortSpawn:rescue?.position??tasks[1]!.position,
    interactMs:3000,extractMs:last.durationMs,interactionRadius:2.8,extractionRadius:5,world,guards,tasks,
    objectives:{relay:first,rescue:tasks[1]!,extract:last}}
})
